"""FABLE memory: files are the durable state; the context window is a cache.

Design stance (see docs/05-memory-context.md): a long-horizon agent should be
able to die at any moment and a fresh session should reconstruct everything
that matters from disk. So memory is plain markdown and JSON under one root --
greppable, diffable, human-auditable. No embeddings, no database: for code and
project state, just-in-time retrieval (grep/read over an index) beats RAG, and
a file the human can open beats a vector the human cannot.

Layout (exact paths -- other modules and the docs rely on them):

    MEMORY.md                     index, <=150 lines, regenerated by garden()
    lessons/YYYYMMDD-<slug>-<digest>.md
                                  one lesson per file, <=30 lines, first line
                                  is a one-line trigger condition
    state/progress.md             append-only journal, newest entry FIRST
    state/plan.md                 current Blueprint, overwritten each plan
    state/feature_list.json       [{category, description, steps, passes}]
    scratch/                      spill target, wiped on session start

Honesty note: none of this makes the model remember anything. Files buy
*resumability* and *cost* (a fresh 0-token session instead of a bloated one),
never per-step correctness. The model re-reads what you saved with exactly
the comprehension its weights provide.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Iterable, Sequence

if TYPE_CHECKING:  # runtime import would climb the DAG; memory sits near the bottom
    from fable.client import FableClient

_INDEX_MAX_LINES = 150
_LESSON_MAX_LINES = 30
_PROGRESS_KEEP_CHARS = 200_000  # progress.md is append-only but not unbounded


class ContainmentError(ValueError):
    """A path tried to escape the memory root (``../``, absolute, or encoded)."""


# --------------------------------------------------------------------------- #
# Secret redaction: applied to EVERY write. Memory files get committed, pasted
# into prompts, and shipped in bug reports -- a leaked key in MEMORY.md is a
# leaked key everywhere.

_SECRET_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"sk-[A-Za-z0-9_\-]{16,}"),                       # API-key shapes
    re.compile(r"AKIA[0-9A-Z]{16}"),                             # AWS access key ids
    re.compile(r"ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{5,}"),  # JWTs
    re.compile(
        r"-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----",
        re.DOTALL,
    ),
)
_KV_SECRET = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|passwd|authorization)\b(\s*[:=]\s*)\S{8,}"
)


def redact(text: str) -> str:
    """Replace secret-shaped substrings with ``[REDACTED]``.

    Pattern-based, so it catches shapes (key prefixes, JWTs, PEM blocks,
    ``key=value`` assignments), not meanings. It is a seatbelt, not a vault:
    keep real secrets out of agent-visible text in the first place.
    """
    for pattern in _SECRET_PATTERNS:
        text = pattern.sub("[REDACTED]", text)
    text = _KV_SECRET.sub(lambda m: f"{m.group(1)}{m.group(2)}[REDACTED]", text)
    return text


def _slug(text: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len] or "note"


def _today() -> str:
    return _dt.date.today().strftime("%Y%m%d")


def _now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class Checkpoint:
    """The ONLY content that survives a session boundary by design.

    Everything else reconstructs from disk and git: code state from the
    working tree, history from ``git log``, task state from
    ``feature_list.json``. The checkpoint carries what the filesystem cannot:
    intent, rejected alternatives, and the next three concrete moves.
    """

    goal: str
    decisions: tuple[str, ...]        # decision + why (the "why" is the payload)
    files_touched: tuple[str, ...]    # paths only, never contents
    verified_done: tuple[str, ...]    # each item should carry evidence ids
    open_issues: tuple[str, ...]
    next_steps: tuple[str, ...]       # exactly the next 3 -- more is a plan, not a step
    lessons: tuple[str, ...]

    def to_markdown(self) -> str:
        def section(title: str, items: Iterable[str]) -> str:
            body = "\n".join(f"- {item}" for item in items) or "- (none)"
            return f"## {title}\n{body}\n"

        return (
            f"# Checkpoint {_now_iso()}\n\n"
            f"## Goal\n{self.goal}\n\n"
            + section("Decisions (and why)", self.decisions)
            + section("Files touched", self.files_touched)
            + section("Verified done (with evidence ids)", self.verified_done)
            + section("Open issues", self.open_issues)
            + section("Next steps (do these, in order)", self.next_steps)
            + section("Lessons", self.lessons)
        )


class Memory:
    """File-based memory store rooted at one directory.

    Importable and constructible with no API key; :meth:`garden` accepts an
    optional client only for compressing an oversized index.

    Reliability inversion (load-bearing): :meth:`mark_passed` is the ONLY
    code path that flips ``passes: true`` in ``feature_list.json``. It is
    called by the gate after evidence exists -- never by the model. A model
    that can mark its own work done will mark its own work done.
    """

    def __init__(self, root: Path | str = ".fable/memory"):
        self.root = Path(root).resolve()
        self.lessons_dir = self.root / "lessons"
        self.state_dir = self.root / "state"
        self.scratch_dir = self.root / "scratch"
        for d in (self.root, self.lessons_dir, self.state_dir, self.scratch_dir):
            d.mkdir(parents=True, exist_ok=True)
        # scratch/ is session-scoped by contract: wipe on start so stale spill
        # files from a dead session are never mistaken for current evidence.
        for entry in self.scratch_dir.iterdir():
            if entry.is_dir():
                shutil.rmtree(entry, ignore_errors=True)
            else:
                entry.unlink(missing_ok=True)

    # ---------------------------------------------------------------- #
    # containment + write discipline

    def _contained(self, relative: str | Path) -> Path:
        """Resolve a path INSIDE the memory root or raise ContainmentError.

        Rejects absolute paths, ``..`` segments, and percent-encoded dot
        variants before resolving, then re-checks with ``resolve()`` +
        ``relative_to()`` (symlinks are resolved away).
        """
        raw = str(relative)
        if "%2e" in raw.lower() or "%2f" in raw.lower():
            raise ContainmentError(f"Encoded path traversal rejected: {raw!r}")
        candidate = Path(raw)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise ContainmentError(f"Path must be relative and inside the root: {raw!r}")
        resolved = (self.root / candidate).resolve()
        try:
            resolved.relative_to(self.root)
        except ValueError:
            raise ContainmentError(f"Path escapes memory root: {raw!r}") from None
        return resolved

    def _write(self, relative: str | Path, content: str) -> Path:
        path = self._contained(relative)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(redact(content), encoding="utf-8")
        return path

    # ---------------------------------------------------------------- #
    # index + boot

    def index(self) -> str:
        """MEMORY.md contents, capped at 150 lines.

        This is the ONLY memory content that enters a boot context wholesale.
        Everything else is fetched just-in-time by grep/read -- the denylist
        in docs/05 exists because dumping the memory dir into context is how
        windows die.
        """
        index_path = self.root / "MEMORY.md"
        if not index_path.exists():
            self._reindex()
        lines = index_path.read_text(encoding="utf-8").splitlines()
        if len(lines) > _INDEX_MAX_LINES:
            kept = lines[:_INDEX_MAX_LINES]
            kept.append(f"... (truncated at {_INDEX_MAX_LINES} lines; run garden())")
            return "\n".join(kept)
        return "\n".join(lines)

    def boot_context(self) -> str:
        """What a fresh session reads first: the index plus the current plan."""
        parts = [self.index()]
        plan = self.state_dir / "plan.md"
        if plan.exists():
            parts.append("## Current plan (state/plan.md)\n" + plan.read_text(encoding="utf-8"))
        return "\n\n".join(parts)

    def resume_prompt(self) -> str:
        """The fixed resume litany. Filesystem rediscovery over summaries.

        A fresh session following these six steps reconstructs more reliably
        than any summary, because summaries rot and disk does not.
        """
        litany = (
            "You are resuming an interrupted run. Reconstruct state from disk "
            "BEFORE acting:\n"
            "1. Print the working directory and list it; confirm where you are.\n"
            "2. If this is a git repo, read `git log --oneline -10` -- what "
            "actually landed, not what was claimed.\n"
            "3. Read state/progress.md (newest entry first) for what previous "
            "sessions did and why.\n"
            "4. Read state/feature_list.json; entries with \"passes\": false "
            "are the open work.\n"
            "5. Pick ONE unfinished feature. Do not start several.\n"
            "6. Re-run one smoke check (that feature's verifier command) "
            "before editing anything, to confirm reported state is real state.\n"
            "Trust the filesystem over any summary, including this one."
        )
        latest = self._latest_checkpoint()
        if latest is not None:
            litany += (
                f"\n\nLatest checkpoint ({latest.name}):\n"
                + latest.read_text(encoding="utf-8")
            )
        return litany

    def _latest_checkpoint(self) -> Path | None:
        candidates = sorted(self.state_dir.glob("checkpoint-*.md"))
        return candidates[-1] if candidates else None

    # ---------------------------------------------------------------- #
    # checkpointing + progress

    def checkpoint(self, cp: Checkpoint) -> Path:
        """Persist a checkpoint and prepend a line to the progress journal."""
        stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        path = self._write(Path("state") / f"checkpoint-{stamp}.md", cp.to_markdown())
        self.log_progress(
            f"checkpoint written: {path.name}; goal: {cp.goal[:120]}; "
            f"open issues: {len(cp.open_issues)}; next: "
            + (cp.next_steps[0] if cp.next_steps else "(none)")
        )
        return path

    def log_progress(self, entry: str) -> None:
        """Append-only journal, newest entry FIRST (a resuming agent reads the
        top of the file, not the bottom)."""
        progress = self.state_dir / "progress.md"
        existing = progress.read_text(encoding="utf-8") if progress.exists() else ""
        new = f"- {_now_iso()} {redact(entry)}\n" + existing
        progress.write_text(new[:_PROGRESS_KEEP_CHARS], encoding="utf-8")

    # ---------------------------------------------------------------- #
    # lessons: one per file, deduped

    def add_lesson(self, trigger: str, body: str) -> Path:
        """Write one lesson file, deduped by content and by trigger.

        ``trigger`` is a ONE-LINE condition for when the lesson applies
        ("when pytest passes locally but the gate fails, check cwd") -- it
        becomes the first line so that ``recall()`` and a human skimming the
        directory both hit it first. Bodies are capped at 30 lines: a lesson
        longer than that is a document, and documents go in scratch or docs.

        Returns the existing file's path when a duplicate is detected --
        write-with-dedupe, so a retry loop cannot fill the store with copies.
        """
        trigger = " ".join(trigger.split())  # force one line
        norm = re.sub(r"\s+", " ", body.strip().lower())
        digest = hashlib.sha256(norm.encode("utf-8")).hexdigest()[:16]
        for existing in sorted(self.lessons_dir.glob("*.md")):
            text = existing.read_text(encoding="utf-8")
            first = text.splitlines()[0].lstrip("# ").strip() if text else ""
            existing_norm = re.sub(
                r"\s+", " ", "\n".join(text.splitlines()[1:]).strip().lower()
            )
            if first == trigger or hashlib.sha256(
                existing_norm.encode("utf-8")
            ).hexdigest()[:16] == digest:
                return existing
        lines = body.strip().splitlines()
        if len(lines) > _LESSON_MAX_LINES:
            lines = lines[: _LESSON_MAX_LINES - 1] + ["(truncated to 30 lines)"]
        content = f"# {trigger}\n" + "\n".join(lines) + "\n"
        # The slug is capped at 40 chars, so two DIFFERENT long triggers can
        # share a slug and collide on the same day. A short trigger digest
        # disambiguates them; genuine duplicates never reach here (they returned
        # above), so this only ever separates distinct lessons.
        trigger_digest = hashlib.sha256(trigger.encode("utf-8")).hexdigest()[:8]
        path = self._write(
            Path("lessons") / f"{_today()}-{_slug(trigger)}-{trigger_digest}.md",
            content,
        )
        self._reindex()
        return path

    def recall(self, pattern: str, max_hits: int = 20) -> str:
        """Grep the lesson store (and the index) for a regex.

        Returns ``path:line: text`` matches -- the retrieval model is
        deliberately grep, not embeddings: it is exact, explainable, free,
        and the same tool the agent already uses on code.
        """
        try:
            rx = re.compile(pattern, re.IGNORECASE)
        except re.error as exc:
            raise ValueError(f"Bad recall pattern {pattern!r}: {exc}") from exc
        hits: list[str] = []
        targets = sorted(self.lessons_dir.glob("*.md")) + [self.root / "MEMORY.md"]
        for path in targets:
            if not path.exists():
                continue
            for lineno, line in enumerate(
                path.read_text(encoding="utf-8").splitlines(), start=1
            ):
                if rx.search(line):
                    rel = path.relative_to(self.root)
                    hits.append(f"{rel}:{lineno}: {line.strip()}")
                    if len(hits) >= max_hits:
                        return "\n".join(hits)
        return "\n".join(hits) if hits else f"(no memory matches for {pattern!r})"

    # ---------------------------------------------------------------- #
    # scratch + feature list

    def spill(self, content: str, hint: str) -> Path:
        """Write oversized content to scratch/ and return the path.

        The caller puts the PATH (plus head/tail) in context, never the
        content. Wiped on session start -- scratch is working memory, not
        memory.
        """
        stamp = _dt.datetime.now().strftime("%H%M%S-%f")
        return self._write(Path("scratch") / f"{stamp}-{_slug(hint)}.md", content)

    def mark_passed(self, feature_id: str, evidence_ids: Sequence[str]) -> None:
        """Flip one feature's ``passes`` to true. Gate-only code path.

        ``feature_id`` is either the feature's exact ``description`` or its
        integer index as a string. Raises KeyError when nothing matches --
        silently marking nothing passed is how status lies start.
        """
        path = self.state_dir / "feature_list.json"
        if not path.exists():
            raise KeyError("state/feature_list.json does not exist; nothing to mark")
        features = json.loads(path.read_text(encoding="utf-8"))
        target = None
        if feature_id.isdigit() and int(feature_id) < len(features):
            target = features[int(feature_id)]
        else:
            for feature in features:
                if feature.get("description") == feature_id:
                    target = feature
                    break
        if target is None:
            raise KeyError(f"No feature matches {feature_id!r}")
        target["passes"] = True
        target["evidence"] = list(evidence_ids)
        path.write_text(json.dumps(features, indent=2), encoding="utf-8")
        self.log_progress(
            f"feature passed: {str(target.get('description'))[:100]} "
            f"(evidence: {', '.join(evidence_ids) or 'none recorded'})"
        )

    # ---------------------------------------------------------------- #
    # gardening

    def garden(self, client: "FableClient | None" = None) -> None:
        """Dedupe lessons and rebuild MEMORY.md.

        Deterministic first: exact-content duplicates are removed (oldest file
        wins), then the index is regenerated. If a client is supplied AND the
        index still exceeds 150 lines, one cheap-tier call compresses it --
        that is the only model involvement, and it is optional.
        """
        seen: dict[str, Path] = {}
        for path in sorted(self.lessons_dir.glob("*.md")):
            norm = re.sub(r"\s+", " ", path.read_text(encoding="utf-8").strip().lower())
            digest = hashlib.sha256(norm.encode("utf-8")).hexdigest()
            if digest in seen:
                path.unlink()
            else:
                seen[digest] = path
        self._reindex()
        index_path = self.root / "MEMORY.md"
        lines = index_path.read_text(encoding="utf-8").splitlines()
        if client is not None and len(lines) > _INDEX_MAX_LINES:
            # Local import: keeps memory.py at the bottom of the import DAG
            # for every caller that never gardens with a model.
            from fable.client import FrozenPrefix

            prefix = FrozenPrefix.build(
                "You compress memory indexes. Keep every file path and every "
                "trigger line; drop prose. Output only the compressed index.",
                (),
            )
            turn = client.call(
                prefix=prefix,
                messages=[
                    {
                        "role": "user",
                        "content": (
                            f"Compress to at most {_INDEX_MAX_LINES} lines:\n\n"
                            + "\n".join(lines)
                        ),
                    }
                ],
                role="mechanical",
            )
            if turn.stop_reason != "refusal" and turn.text.strip():
                index_path.write_text(redact(turn.text), encoding="utf-8")

    def _reindex(self) -> None:
        """Regenerate MEMORY.md deterministically from what is on disk."""
        lines = [
            "# MEMORY.md -- index only. Fetch details with grep/read, never dump.",
            f"Updated: {_now_iso()}",
            "",
            "## Lessons (first line of each file is its trigger condition)",
        ]
        lesson_files = sorted(self.lessons_dir.glob("*.md"))
        if not lesson_files:
            lines.append("- (none yet)")
        for path in lesson_files:
            first = path.read_text(encoding="utf-8").splitlines()
            trigger = first[0].lstrip("# ").strip() if first else "(empty)"
            lines.append(f"- lessons/{path.name}: {trigger}")
        lines.append("")
        lines.append("## State")
        feature_path = self.state_dir / "feature_list.json"
        if feature_path.exists():
            try:
                features = json.loads(feature_path.read_text(encoding="utf-8"))
                done = sum(1 for f in features if f.get("passes"))
                lines.append(
                    f"- state/feature_list.json: {done}/{len(features)} features pass"
                )
            except (json.JSONDecodeError, TypeError):
                lines.append("- state/feature_list.json: UNPARSEABLE (fix by hand)")
        if (self.state_dir / "plan.md").exists():
            lines.append("- state/plan.md: current blueprint (read before planning)")
        progress = self.state_dir / "progress.md"
        if progress.exists():
            first_entry = progress.read_text(encoding="utf-8").splitlines()
            if first_entry:
                lines.append(f"- state/progress.md, latest: {first_entry[0][:120]}")
        (self.root / "MEMORY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
